import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";




export const metadata: Metadata = {
  title: "Your connected workspace for wiki, docs & projects | Notion",
  description: "Generated by Esdras Santos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning 
        className={`bg-background w-full h-screen`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
